purify.js
test/index.html

This pull request encompasses the following refinements:
1. Optimise: without changing the semantics, many easy optimisations were made, for example changing from searching an array for allowed tags/attributes [O(n)] to constructing a lookup table [O(1)].
2. Fix small documentation errors, typos and whitespace inconsistencies.
3. Add an "isSupported" property to the DOMPurify object to allow users to easily check if the browser supports the full DOMPurify.
4. Fix a bug where sanitize would return a string even when RETURN_DOM is set, if the input had no "<" character.
5. Always return the full html including browser inferred `<html><body>` etc. tags if WHOLE_DOCUMENT config option is set, even if the input has no "<" character.
The test suite has one modification for (5). No other …

Optimise and refine

---

demos/hooks-mentaljs-demo.html
purify.js

* Tidies code, reordering a few things for more efficient execution, removing
the need to clone the DOM node and caching values in local variables to
reduce object lookup costs.
* Improves the uponSanitizeAttribute hook:
- The hook is now called *before* removing the attribute from the node. This
allows the hook to access any parsed version of the attribute available on
the node (e.g. the "style" attribute).
* The hook no longer passes the attr object itself, since this contains no
extra information beyond the name/value already in the hook data.
* The hook has a new "keepAttr" property, which may be set to `false` by the
hook to reject the attribute even if it would otherwise be kept by the
whitelist.
* The hook function may change the value to be set for the attribute by setting
the …

Tidy, optimise & improve hook in _sanitizeAttributes

---

purify.js
test/expect.json
test/index.html

Safari (latest version on both iOS + Mac) will crash hard if you try to remove a "name" attribute from an image node that also has an "id" attribute. I've filed a bug with Apple, but in the meantime this patch works around the issue.
Also, I've fixed up the tests so they all pass in Safari: it has slightly different behaviour parsing form tags.

Workaround Safari Crash

---

purify.js

This pull request makes the following changes:
1. Preserve contents of <o:p> tag
2. Allow background, cellpadding and cellspacing attributes
This is important for preserving the formatting of many HTML emails. It should not have any security implications.

Allow more benign contents/attributes

---

test/index.html

I am working on fixing failing test cases in jsdom, but the output for many test cases is not very useful. Especially because a large amount of test cases have the same name. This change shows the following info when a case fails:
1. Show the actual output instead of "false"
2. Show a list of all valid expected values
3. Show the payload

Improve logging for assert.contains

---

purify.js
test/expect.json

This issue might be hit if you display sanitized html within your own `<form>` element.
For example:
```html
<form id="test">
<script>
document.write(DOMPurify.sanitize('<input name=submit>123'));
</script>
</form>
<script>
test.submit(); // TypeError: test.submit is not a function
</script>
```

Prevent DOM clobbering on <form> elements

---

.jshintrc
purify.js
test/index.html

This change lets you set up DOMPurify with your own `window` and `document`. It is now super easy to set up with [jsdom](https://www.npmjs.com/package/jsdom):
```javascript
var document = require('jsdom').jsdom();
var DOMPurify = require('dompurify')(document.defaultView);
console.log(DOMPurify.sanitize('<script>alert("hi");</script><p>hello</p>'));
```
For the extra paranoid, you can put jsdom in a mode wherein it never download or execute scripts:
```javascript
var document = require('jsdom').jsdom('', {
FetchExternalResources: false,
ProcessExternalResources: false
});
```
This change is backwards compatible. If you run it in a browser, a `DOMPurify` object is added to the `window`. If you use browserify the following should work exactly like it did before: …

Support for custom `window`

---

purify.js

* `<br clear="both" />`
* `<font face="Arial"></font>`
* `<hr noshade />`
* `<span nowrap>no wrap</span>`
I went through this list: http://www.w3.org/TR/html4/index/attributes.html
Ones I didn't add that seemed maybe reasonable:
----
----
----
Other legacy things we should probably not add:
----
----
----

Add a few more missing legacy attributes

---

purify.js

The _isClobbered fn detects whether any of the methods/attributes we need on
the element have been clobbered. The properties it checks for had not been
updated with the changes in how the sanitisation methods manipulated the
elements, meaning it was making some unnecessary checks, and not making some
required ones, which could result in an error being thrown with certain input.

Update _isClobbered to check currently required properties

---

purify.js

This makes it much easier to implement compatible support in JS DOM
emulation libraries.

Use instanceof instead of toString to check if attributes is clobbered

---

purify.js

For a while, Firefox made the attributes collection an instance of
MozNamedAttrMap instead of NamedNodeMap.

Fix checking attributes type in FF22-34.

---

purify.js

I need this for <linearGradients> inside my <svg> tag.
Apparently, DOMPurify removes the 'offset' attribute.

add 'offset' attribute for gradients of SVG elements

---

README.md
purify.js
test/index.html

Fixes #62
Should work properly even if `SANITIZE_DOM` is disabled.
```javascript
document.body.appendChild(
DOMPurify.sanitize(dirty, {RETURN_DOM_FRAGMENT: true, RETURN_DOM_IMPORT: true})
);
```

RETURN_DOM_FRAGMENT and RETURN_DOM_IMPORT

---

purify.js
test/index.html

Fixes #47 for real, I think. Unless I've misunderstood it, in which case please feel free to reject!
Also implements a better fix for clobbering of required fns on the dirty document; we cache direct references to the fns we need, so it doesn't matter if things get clobbered. This makes the SANITIZE_DOM option more consistent; the behaviour is the same for any name/id that would clobber a method/property in the document/window, regardless of whether we need it internally or not.

Ensure document has blank web-components registry

---

purify.js

The main fix is for the importNode call, which I inadvertently broke when I fixed the clean document creation issue (#47). Also fixes comment nodes incorrectly being returned as clobbered, removes some more unnecessary clobber checks and does a better check for an id needed to workaround the Safari crash bug.

Fix import node + a variety of minor issues

---

purify.js

how did this get in the .js file? oO
This enables us to use font-weight as an attribute in SVGs.

fix stupid typo

---

purify.js

Previously, if you use the KEEP_CONTENT option, the tag had to match a
whitelist for its contents to be kept. This is not necessary for security,
since the contents is still sanitised just like any other content in the page,
and is annoying if you are sanitising random HTML from sources which may use
arbitrary non-standard tags to wrap bits of real content (resulting in chunks
of text being stripped by the sanitiser).
This commit changes the CONTENT_TAGS whitelist to a FORBID_CONTENTS blacklist;
the blacklist is not needed for security, but we do want to remove the contents
of <script> tags, style tags (if <style> has been disallowed) and anything in
the <head> (if disallowed), since we know these are not designed to have
user-visible content.
Implements #65, since no one objected in the …

Change CONTENT_TAGS to blacklist

---

purify.js
test/expect.json
test/index.html

Fix up expected results for tests with the changed KEEP_CONTENT behaviour.
Tests now all pass again in latest Chrome, Firefox & Safari (not tested in IE, sorry; I don't have it handy).
(Sorry, forgot to do this before sending the pull request that actually changed the behaviour).
Also a small commit to add a couple of extra tags, which if excluded we should skip the content of.

Fix up tests

---

purify.js
test/index.html

Stripping out `<form>` elements with clobbered `parentNode` crashes DOMPurify.

Fix form aliasing crash

---

purify.js
test/index.html

HTML5 allows a broad range of characters for [data-* attribute names](https://html.spec.whatwg.org/multipage/dom.html#embedding-custom-non-visible-data-with-the-data-*-attributes), but DOMPurify [further limits them](https://github.com/cure53/DOMPurify/blob/7a031e3232642acd8bbc952015d8c4c229cb40db/purify.js#L479) to alphanumerics, underscores, and hypens. This PR relaxes those and further relies on `setAttribute` to catch truly invalid names, and additionally avoids regex redefinition.

Accept non-alphanumeric data-* attributes

---

bower.json

Hi,
the [bower-license-spec](https://github.com/bower/bower.json-spec) specifies the license entry in the `bower.json` to be either a string, an array of strings or an url to the license file. Tools such as [bower-license](https://www.npmjs.com/package/bower-license) run into trouble when the spec is not followed.
I updated the `bower.json` the have a license entry of type array of strings. I hope it's possible for you guys to merge this back into master.
Cheers

Fix license requirement in bower.json to follow bower-license-spec.

---

.travis.yml
package.json

- jshint now lints `src/purify.js`
- sudo:false flag addded to `travis.yml` for container-based infrastructure

Add sudo:false and fix jshint linting correct file.

---

README.md
demos/advanced-config-demo.html
demos/basic-demo.html
demos/config-demo.html
demos/hooks-demo.html
demos/hooks-link-proxy-demo.html
demos/hooks-mentaljs-demo.html
demos/hooks-proxy-demo.html
demos/hooks-removal-demo.html
demos/hooks-sanitize-css-demo.html
demos/hooks-scheme-whitelist.html
demos/hooks-target-blank-demo.html
website/index.tpl

This replaces all occurrences of `purify.js` to `src/purify.js` and therefore closes #97. Along furthermore removes all trailing whitespaces from demo files.

Fix using purify.js from /src folder in demos and index.tpl.

---

package.json

> Less verbose logs for TravisCI run than previously produced by `progress` reporter.
This changes the log level to `warn` from `info` and adds the `dots` reporter to a karma run on TravisCI. The dots reporter is meant to be way less verbose.
Still I hope errors get reported nicely too. Still, the local run triggered by `npm run-script ci-test` will still make use of the `progress` reporter and therefore give more detailed output.

Add dots reporter to karma run on TravisCI.

---

src/purify.js

Hey, guys!
After taking an overview at DOMPurify, I have a few concerns. This pull request tries to address them as explained below:
At line no. 393 and its following line, you're clearly making use of the `m` modifier within these couple regular expressions: `/\{\{.*|.*\}\}/gm` and `/<%.*|.*%>/gm`; that, in fact, has absolutely no effect on the dot meta-character in ECMAScript! I guess you meant to match new lines with that (or line terminators `[\n\r\u2028\u2029]` in general), but the right way to do so is by using a character class as such `[\s\S]`.
Another concern is, at line no. 470, you're making use of a blacklist regex to detect evil URI schemes like `javascript:`, and you are doing it well (albeit, this has been bypassed before). But given that it will only match at the very …

Improve code quality and robustness

---

src/purify.js

As per #138, use a simpler regex for IS_ALLOWED_URI. Also cleans up the big `if` condition to make it easier to understand.

Simplify attribute sanitisation.

---

package.json
test/fixtures/expect.js
test/jsdom-node-runner.js
test/jsdom-node.js
test/purify.min.spec.js
test/purify.spec.js
test/test-suite.js

Also see #129
There is one failing test because of https://github.com/tmpvar/jsdom/issues/1460, which is why I have not yet added this new task to the CI script.
The new file `test/jsdom-node.js` is using ES6 syntax because jsdom requires that same syntax, so this test suite will fail early if someone tries to run it with a node.js version that is too old. I could easily change this if you all would like to enforce ES5 as a style requirement.
I am not that familiar with QUnit, so could someone double check that part? For example, is the `qunit` npm package a good runner for it? (I have noticed that it uses an older version of `qunitjs`, so we end up with two versions of `qunitjs`)

Also run unit tests using jsdom + Node.js

---

package.json

I ran all tests with node@4 on against another BrowserStack account and they all worked fine now three times in a row.
I am unsure why karma hangs with browser.on is not a function as it is mentioned in issues long merged and released. The update - away from the fork - of the karma-browserstack-launcher could maybe have caused dropping connection.
Let me know if this helps whenever your rate limits comes back to life. I hope you/we can find a sponsor for this project. Do you have any clue how much runs - build time this actually causes?

Update karma-browserstack-runner and fix karma log level

---

src/purify.js

2 minor fixes and one major security patch:
The logic for whether to forbid an attribute was broken: if
ALLOW_UNKNOWN_PROTOCOLS was true, then it would allow any attribute with
a value that didn't match the IS_SCRIPT_OR_DATA regexp.
This evades the attribute name whitelist, and is a security flaw: for
example you could set any "onFoo" JavaScript attribute.
The logic here got too convoluted to be easy to read, which is
presumably how this bug crept in. I have rewritten it into an expanded
set of if/else statements which I believe are easier to follow.

Attr security flaw

---

bower.json
package.json

Removes tests, demos, build scripts, etc. from package manager distribution
to keep the overall file size down and improve installation speed.
- package.json: Only include files in 'src' and 'dist' in npm
- bower.json: Ignore all files except for 'src' and 'dist' for bower

Reduce package footprint

---

demos/hooks-scheme-whitelist.html

We just caught an issue in @cyph that was causing links sent in succession to break as in the attached screenshot, and this turned out to be the culprit.
From the MDN docs on RegExp.test: "As with exec() (or in combination with it), test() called multiple times on the same global regular expression instance will advance past the previous match."
Test for comparison:
```
const regex0 = /^(http|https|ftp):/gim
const regex1 = /^(http|https|ftp):/im
regex0.test('https:')
true
regex0.test('https:')
false
regex0.test('https:')
true
regex0.test('https:')
false
regex1.test('https:')
true
regex1.test('https:')
true
regex1.test('https:')
true
regex1.test('https:')
true
```

Minor fix for URI scheme whitelist demo hook

---

src/purify.js

The logic was inverted, so this was broken in *both* the Safari and Firefox
edge cases.
This replaces it with a simpler test, which I have confirmed is right in both Safari and Firefox. One question though: why was this not picked up by the automated tests? The test suite should have failed in Safari 10.1 with 0.8.7, and I thought you had added this to the browser matrix?

Fix broken test for useDOMParser

---

package-lock.json
package.json
test/karma.conf.js
yarn.lock

The karma-rollup-plugin we were using got deprecated and was not updated with the latest changes in the rollup API. This migrates towards the new karma-rollup-preprocessor which is recommended instead.
This could also fix our build problems which I sadly can't reproduce but will look into more later this weekend by having PRs run at least against one random browser on browserstack.
Sorry again for the trouble and lets hope that this fixes the issue of CI on master so 1.0.1 can be relased.

Upgrades karma-rollup plugin

---

README.md

Demonstrating DOMPurify usage with the older JSDOM API
> This pull request updates the readme to show an example of DOMPurify working with the older JSDOM API for server side rendering
Should clarify usage for anyone still using the old JSDOM api.

Update code example to show usage with older JSDOM API

---

src/attrs.js

> This pull request whitelists preserveAspectRatio
I want to use preserveAspectRatio with my SVGs to control scaling. This should be a straightforward change. MDN in case anyone's curious: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/preserveAspectRatio
- Nothing?
None?

Whitelist preserveAspectRatio

---

README.md

> This pull request changes the `README.md` file to add two new badges
These badges are always pointing to the latest npm version and find the display the size of the `purify.min.js` gzipped for the browser as well as the total install size after npm install.
- Add tasks to give a quick overview for QA and reviewers
If there are any dependencies on PRs or API work then list them here.

Add badges to display gzip size and install size

---

package.json

> This pull request changes `package.json` so that npm publish only publishes the dist folder plus the default file such as README.md
npm is pretty smart and already figures out which files are necessary and which ones are not https://docs.npmjs.com/files/package-lock.json
You can see how dompurify used to avoid publishing these files and has since grown in size: https://packagephobia.now.sh/result?p=dompurify
- Add tasks to give a quick overview for QA and reviewers
If there are any dependencies on PRs or API work then list them here.

Change npm publish to "dist" only

---

src/purify.js
test/test-suite.js

This pull request allows for the sanitization/blacklisting of `<input type="file" />` by setting the hookEvent keepAttr to false.
Currently an [AMP HTML](https://github.com/ampproject/amphtml)  spec disallows for the following usage in templates: input[type=file]
DOM Purify does not allow for the sanitization of the type `file` because of a Safari bug which doesn't permit the adding back of this attribute once removed. See https://github.com/cure53/DOMPurify/blob/master/src/purify.js#L843

sanitize input[type=file] if hookEvent.keepAttr is false

---

src/purify.js

RegExp.test() returns a boolean whereas String.match() returns an array
of match results, requiring object allocation and adding GC pressure.
If match results are not needed then RegExp.test() is faster.

Use RegExp.test() instead of String.match()

---

demos/hooks-node-removal2-demo.html

This PR adds a demo of removing nodes when you only want to allow a subset of tags, which is not covered by the existing node removal demo.
See https://github.com/cure53/DOMPurify/issues/388
Just open the new demo page in the browser.
There are no dependencies

Adding a new example for node removal

---

README.md

> This pull request adjust a invalid sanitize example in the readme
The example has a missing closing `</p>` tag

docs(readme): adjust invalid sanitize example

---

src/attrs.js

This pull request adds [`startOffset`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/startOffset) to the list of allowed SVG attributes.
When using DOMPurify to sanitize SVGs that include the `startOffset` attribute, the sanitize process removes the `startOffset` attribute, causing a visual breakage. The [MDN docs](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/startOffset) provide a good example that illustrates the visual difference when `startAttribute` is applied vs not applied:
There are no known security concerns associated with this attribute, and other major open source libraries include it in their safelists (including [React](https://github.com/facebook/react/blob/8cb2fb21eb4e931b80d8b0502059061891ac4563/packages/react-dom/src/shared/possibleStandardNames …

add startOffset to svg allowed attrs

---

test/karma.custom-launchers.config.js

With GitHub Actions these args are not always set cause we evaluate them as expressions in the workflow file. On TravisCI we hoped that an env variable would be set. That simplifies things here and allows it to be more explicit.
I noticed cause we currently run both Node.js v13 and v12 in the matrix against BrowserStack which is not needed cause we evaluated for anything but an empty string to trigger it :)

fix: argv parsing with github actions

---

src/license_header

This `@license` is what Google Closure Compiler and hence terser uses to preserve the comment. There is also a `@preseve` but this feels more meaningful.

fix: add @license to comment

---

rollup.config.js

> This pull request fixes the license header to be added.
The license header's file content was read into a buffer:
Rollup doesn't prepend buffers if specified as the banner. We now read the license as utf-8. This adds it to the dist files.

fix: license header not being added

---

package.json

Closes #427.
node and nvm are not used at runtime by DOMPurify.
They initially have been introduced by c9661e1a4c2e32b0ad87807b12eb33edc1361095 which looks like a painful debugging session

Move node and nvm to the dev dependencies

---

src/purify.js

Some code returns a `trustedHTML` value without confirming `RETURN_TRUSTED_TYPE`. This PR is for adding the check.

Fix lack of RETURN_TRUSTED_TYPE check

---

demos/advanced-config-demo.html

The advanced config demo incorrectly assigned `innerHTML` from a DOM node
instead of a string.

Fix advanced config demo

---

README.md

This pull request fixes a few broken links that were pointing to the outdated `master` branch.
The default branch name must have been changed recently 🖤, and these README links are out of date.
grepping the repo for `master` gives these results below. I've fixed the basic README links. Someone with more context is welcome to amend/follow-up with additional fixes.
- Test out the few updated links to make sure they are working now

Update README references to `main` branch

---

dist/purify.cjs.js
dist/purify.js
src/purify.js

There is a small typo in dist/purify.cjs.js, dist/purify.js, src/purify.js.
Should read `return` rather than `retrun`.

docs: Fix simple typo, retrun -> return

---

README.md

The flag was removed in 661571886064ee7465bcf7d295cfe5038beab9a4, other documentation about it was removed in 8177881230f019d5d7c6e607f8dbe65e28138c82.

Remove mention of the removed SAFE_FOR_JQUERY flag in README

---

src/license_header

Update The header to match the current version of the npm package 
Firefox rejected an update to an extension on their store saying the version is not updated and has security issues, but is the updated version, just with bad header
> This pull request [implements, fixes, changes]...
Changes
The version number on the license header is old, resulting on mismatch for some requirements even if the code is the latest code.
For example when using just the DIST version inside a browser extension, the review team (firefox for example) checks there for the version and they need it to be up to date
- Add tasks to give a quick overview for QA and reviewers
No dependencies

Update license Header to match current Version

---

test/fixtures/expect.js

> This pull request is a quick to the playground at https://cure53.de/purify
The playground currently raises a syntax error due to the training comma in the test JS file that is converted to JSON.

Fixed playground syntax error

---

README.md

> This pull request adds a new comment to the existing list of code examples in the README.
Added a comment at the first occurrence of the `USE_PROFILES` setting to warn that it will override an existing `ALLOWED_TAGS` setting. We had discussed this in issue #507.
- Ensure that this is indeed the correct place to add the comment
- If not, please suggest another place to add this comment
I will be creating another PR for the demos README to add an example config.

Updated README as discussed in issue #507

---

src/purify.js
src/utils.js

> This pull request fixes an issue for lookupGetter utility.
When there is no entries for properties, it returns null. Instead as a fallback the utility could return a function, which could be used i.e. to get nullable parent node.

add fallback for lookup-getter util

---

src/attrs.js

Currently content within custom elements will have their `slot` attribute removed. This attribute is standard HTML and should not be stripped. This pull request adds the `slot` attribute to the safe list.
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/slot

Adding missing `slot` attribute

---

src/purify.js
test/test-suite.js

> This pull request [implements, fixes, changes]...
https://github.com/cure53/DOMPurify/issues/556
If there are any dependencies on PRs or API work then list them here.

Expose `FORBID_CONTENTS` to allow users to specify which elements DOMPurify should remove from the input with its children

---

README.md

> This pull request fixes README.md for `PARSER_MEDIA_TYPE`
https://github.com/cure53/DOMPurify/pull/568 introduces XML parsing by specifying application/xhtml+xml as `PARSER_MEDIA_TYPE`. Any other type is parsed as text/html, if I understand correctly. The README.md said to use application/xml for XML parsing, which is thus incorrect.
none
none

Fix README.md to reference application/xhtml+xml

---

demos/README.md

docs: fixed typo on README for demos

---

README.md
test/karma.custom-launchers.config.js

Replaced descriptions about Travis with GitHub Actions
This project no longer uses Travis CI.

docs: remove descriptions about travis

---

.github/workflows/build-and-test.yml

updated comments to use `main` instead of `master`
This project's default branch is `main`.

chore: updated comments to use main instead of master

---

package-lock.json
package.json
test/karma.custom-launchers.config.js

This PR removes deprecated package `llodash.isarray`.
https://www.npmjs.com/package/lodash.isarray
> This package is deprecated. Use Array.isArray.
https://caniuse.com/?search=isarray

chore: remove deprecated lodash.isarray

---

src/attrs.js

> This pull request adds the `transform_origin` to the list of allowed attributes in the SVG filter. 
This attribute is used to assign an origin about which to transform objects in an SVG. It's analogous to the `transform` attribute, which is currently allowlisted. 
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform-origin
- If this attribute introduces a XSS risk, or requires further discussion, I can turn this PR into a draft and file an issue instead :)

Allow `transform-origin` attribute in SVGs

---

package-lock.json
package.json

This PR removes deprecated package `babel`.
The package has been deprecated.
https://www.npmjs.com/package/babel
> In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers
Also, it seems this project doesn't depend on the package so I guess we can remove it simply.

chore: remove deprecated package babel

---

test/test-suite.js

This PR formats the code.
I found formatting produces diffs. Maybe the code was not formatted in https://github.com/cure53/DOMPurify/commit/262a050fb353911b79977404e93831a11cbd528a.

chore: run format

---

package-lock.json
package.json

This PR updates `karma-firefox-launcher` to the latest version.
https://github.com/karma-runner/karma-firefox-launcher/blob/master/CHANGELOG.md
> Changed minimum required version of node.js from 8 to 10.
This project's CI does not cover Node.js 8, so I don't think the breaking change will affect it.

chore: bump karma-firefox-launcher

---

test/purify.spec.js

This PR fixes importing path for `purify`
I found [this PR](https://github.com/cure53/DOMPurify/commit/991491212e5e88b446058609d68f3b3205e3a9d9#diff-bbbda76b86d3bdd2a249ec0e11c054d82317e1d752fc13343a934802e21c2e28) changed both `purify.spec.js` and `purify.min.spec.js` to import `purify.min`.
But `purify.spec.js` should test `purify`, not `purify.min`.

chore: fix import path for testing

---

test/config/setup.js
test/jsdom-node.js

This PR fixes CI failure on IE11.
https://github.com/cure53/DOMPurify/runs/5175145927?check_suite_focus=true
> IE 11.0 (Windows 8.1) ERROR
>  Expected ':'
>  at test/config/setup.js:10:13

chore: fix test on IE11

---

test/test-suite.js

This PR changes to use an unused `tests` variable correctly.
In the unit tests, `tests` variable is declared but it is unused since `forEach` method is chained directly.

chore: use unused variable

---

README.md

This PR fixes the link to jsdom.
- jsdom repository is now under jsdom org.

chore: fix link to jsdom

---

README.md

This PR updated the link to the bug bounty info.
The page is now redirected to https://www.fastmail.com/about/bugbounty/

chore: fix link to bug bounty info

---

README.md

This PR fixes the link to Trusted API.
The page is redirected to https://github.com/w3c/webappsec-trusted-types

chore: fix link to trusted api

---

README.md

This PR updates the link to AMD.
https://github.com/amdjs/amdjs-api/wiki/AMD
> This is a copy of the ["AMD" document in the repo](https://github.com/amdjs/amdjs-api/blob/master/AMD.md), kept here to maintain historical links. If this document differs from the one in the repo, the repo version is the correct one.

chore: fix link to AMD

---

SECURITY.md

This PR updates the link to the bug bounty page. 
https://www.fastmail.com/about/bugbounty.html is redirected to https://www.fastmail.com/about/bugbounty/

chore: update the link to bug bounty page

---

src/purify.js
src/utils.js
test/test-suite.js

A while back we introduced PARSER_MEDIA_TYPE option for parsing XHTML files where tag and attribute names are case-sensitive. 
We have one use case where we would like DOMPurify to keep certain custom tags and attributes by specifying ALLOWED_TAGS and ALLOWED_ATTR options. The problem is that `addToSet` function forces lowercase by calling `stringToLowerCase` on all elements. DOMPurify therefore does not respect ALLOWED_TAGS and ALLOWED_ATTR options and always removes our custom tags and attributes. 
This PR fixes this issue by passing `transformCaseFunc` to `addToSet`, happy to redo if there is a better way to do it.

Make TAG and ATTR cfg options case-sensitive when parsing XHTML

---

.github/PULL_REQUEST_TEMPLATE.md
test/test-suite.js

This PR formats the code by `npm run format`.
There were some unformatted codes.

format code

---

package-lock.json
package.json

This PR updates the outdated jsdom package version.
https://github.com/jsdom/jsdom/blob/master/Changelog.md
But mainly, they updated to [parse5 7.0.0](https://github.com/inikulin/parse5/releases/tag/v7.0.0)

chore: bump jsdom

---

README.md

The value in readme seems to be incorrect. The comment above informs us that if we pass false as a value, then no customized built-ins are allowed.
- xxxx
- xxxx
- xxxx

chore: fix allowCustomizedBuiltInElements value in readme

---

src/purify.js

Use TrustedHTML instead of raw string when assigning empty string to Element.innerHTML sink. This should fix #747 .

Fix Trusted Types Sink violation with empty input and NAMESPACE

---

src/tags.js

DOMPurify now removes the <mprescripts/> . tag
Causes the formula part of the CKEditor library to display an error
correctly display CKEditor's Math formula
add 'mprescripts' to mathML
- use formula in ckeditor
exam 
-input : "<p><math xmlns=\"http://www.w3.org/1998/Math/MathML\" class=\"wrs_chemistry\"><mmultiscripts><mi mathvariant=\"normal\">P</mi><mprescripts/><mn>200</mn><mn>190</mn></mmultiscripts></math></p>\n"
-output: "<p><math xmlns=\"http://www.w3.org/1998/Math/MathML\" class=\"wrs_chemistry\"><mmultiscripts><mi mathvariant=\"normal\">P</mi><mn>200</mn><mn>190</mn></mmultiscripts></math></p>\n"

add tag mprescripts to mathMl

---

src/purify.js

`shadowrootmod` should be `shadowrootmode`.

Fixed a typo in shadowrootmode attribute

---

README.md

Hello 👋 @cure53 
I think the current "README.md" is pretty good, but I've made some changes for readability and consistency.
In the case of "Can I configure DOMPurify?", all the example code is crammed into one code box, which I think is bad for readability. 
I read the "README.md" and thought it could be improved, so I created a pull request. 
Please review this pull request to see if it's appropriate. 🙏
- Update README.md

docs(purify): Update README.md

---

src/utils.js

console.warn(element) is displaying a lot of stuff, in some context like HappyDom this displaying a lot of stuff because a recursive console output of the entire Dom.
I was thinking of the other solutions
* Change the way of displaying a element in Happydom
* Remove the display of the element in the warn
- Could someone give me some context when this fallback function is called
`fallback value for <b>by SMS</b>` when calling `DOMPurify.sanitize('The patient will receive a link <b>by SMS</b> to join the video consultation')` so why `<b>by SMS</b>` will be an element considered as a fallback ?
https://github.com/cure53/DOMPurify/blob/756cec35240cefe261aab06be1e0a7a1e66a6b19/src/purify.js#L114-L120
Could be Happydom not implementing the same way the API for `<b>` ?
As now it seems Dompurify …

console warn fallback for <b> when run with Happydom

---

README.md

this pull request changes hook usage example 
now hookEvent is passed **only** for `uponSanitizeAttribute` hook.
currently there is misleading example of hook usage, where the `beforeSanitizeElements` hook is used.
in order to avoid misunderstandings and simplify life for next users of lib, let's correct this mistake.

docs(README.md): correct hook name in example and remove misleading comment

---

src/purify.js
test/fixtures/expect.mjs
test/karma.custom-launchers.config.js
test/test-suite.js

Fix typos found in comments and test descriptions.
Run codespell.

fix(typo): found by `codespell`

---

dist/purify.cjs.d.ts
dist/purify.es.d.mts
src/purify.ts

This PR exports the `Config` type from DOMPurify, so that people can do:
```ts
import type {Config} from 'dompurify';
// or
type Config = import('dompurify').Config;
```
This is to more closely match [@types/dompurify][1], which allows it, to make migration easier for any TypeScript users that currently use `@types/dompurify`.
[1]: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a0058c8132907c88b6e4d3dd0f4103f799deb732/types/dompurify/index.d.ts#L59
N/A
N/A

fix(types): export `Config` type from package

---

package.json

Moved the "import" conditional export to be defined first.
Conditional exports are processed in order:
> Within the ["exports"](https://nodejs.org/api/packages.html#exports) object, key order is significant. During condition matching, earlier entries have higher priority and take precedence over later entries. The general rule is that conditions should be from most specific to least specific in object order.
> 
> https://nodejs.org/api/packages.html#conditional-exports
As far as I understand, this means the "imports" should be defined first so that it takes precedence over "require" or "default".
Thank you @ghiscoding for pointing this out in https://github.com/cure53/DOMPurify/issues/1018#issue-2653000713.
I've also changed "require" to "default" so that it's the catch-all fallback.
N/A …

Moved the "import" exports to be first

---

dist/purify.cjs.d.ts
scripts/fix-cjs-types.js

fixes #1018
Fixes issue #1018 by simply ignoring the TypeScript error since the TS error has no negative effect whatsoever on the functionality of these types. This makes TypeScript and "Are the Types Wrong" both happy and everything is back to normal and we can get back to work (finally).
The quick explanation is that sometime even when using ESM imports, CJS types exports get picked up (depending on the users tsconfig module resolutions) and `export = ...` is a TypeScript error, but we can easily patch it by ignoring it. 
I found this article [Default exports in CommonJS libraries](https://blog.andrewbran.ch/default-exports-in-commonjs-libraries/) which explains why `export = _default` was patched in the first place. However this gives a TypeScript error in some cases (depending on your …

fix: ignore export assign cannot be used in module TS error, fixes #1018

---

dist/purify.cjs.d.ts
dist/purify.es.d.mts
src/purify.ts

Export DOMPurify interface

---

dist/purify.cjs.d.ts
dist/purify.es.d.mts
src/purify.ts

this PR properly marks the createDOMPurify/DOMPurify ctor param as optional, since it has a default defined. it also documents said default.
this broke my build when updating ^^
thanks for taking the time to add types tho, one less @types package :)
none
none

fix: mark createDOMPurify param as optional

---

package.json

This PR is per discussions had in the issue:
- https://github.com/cure53/DOMPurify/issues/1050
<br />
Adds `purify.js` and minified `purify.min.js` to the package.json **exports** field, allowing for each script to be called as it was prior to DOMPurify v3.2.0. 
DOMPurify was migrated over to utilizing exports in commit `faf296da9b412d93023dde1c8f86599cb7b13beb` and is provided in the link below:
- https://github.com/cure53/DOMPurify/commit/faf296da9b412d93023dde1c8f86599cb7b13beb#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R29-R41
```json
"exports": {
".": {
"require": {
"types": "./dist/purify.cjs.d.ts",
"default": "./dist/purify.cjs.js"
},
"import": {
"types": "./dist/purify.es.d.mts",
"default": "./dist/purify.es.mjs"
}
}
},
```
DOMPurify v3.1.7 is the last …

chore(package.json): add `purify.js` and `purify.min.js` to exports as targetable modules

---

test/test-suite.js

1. Improved the "DOMPurify custom window" test to ensure that the `document` and `window.Element` are tested separately.
2. Increased the likelihood of the test failing if a new `window` property is required in the future, thereby reducing the risk of future `TypeError: Cannot read properties of undefined` errors.

tests: DOMPurify custom window test improvement

---

package.json

This pull request tries to solve a similar issue as described in: https://github.com/cure53/DOMPurify/issues/1050 and fixed in https://github.com/cure53/DOMPurify/pull/1053
In our case we are importing this lib via `dompurify/dist/purify.js`. Which fails with the recent versions of this lib since the `exports` field was introduced with this error message:
```
Error: Module not found: Error: Package path ./dist/purify.js is not exported from package node_modules/dompurify (see exports field in node_modules/dompurify/package.json)
```
I won't go to much into details here as it is basically the same story as in https://github.com/cure53/DOMPurify/pull/1053.
This could probably also be solved by anyone using this lib by adapting the import of this lib from `dompurify/dist/purify.js` to …

chore(package.json): add `dist/purify.js` and `dist/purify.min.js` to exports as targetable modules

---

.github/workflows/build-and-test.yml
package.json
typescript/commonjs-with-no-types/index.ts
typescript/commonjs-with-no-types/tsconfig.json
typescript/commonjs-with-no-types/types/readme.md
typescript/commonjs-with-specific-types/index.ts
typescript/commonjs-with-specific-types/tsconfig.json
typescript/commonjs/index.ts
typescript/commonjs/tsconfig.json
typescript/esm-with-no-types/index.ts
typescript/esm-with-no-types/package.json
typescript/esm-with-no-types/tsconfig.json
typescript/esm-with-no-types/types/readme.md
typescript/esm-with-specific-types/index.ts
typescript/esm-with-specific-types/package.json
typescript/esm-with-specific-types/tsconfig.json
typescript/esm/index.ts
typescript/esm/package.json
typescript/esm/tsconfig.json
typescript/nodenext/index.ts
typescript/nodenext/tsconfig.json
typescript/package.json
typescript/verify.js

This pull request adds an npm script called `verify-typescript` that will attempt to compile some TypeScript projects with different configurations that use DOMPurify.
See #1035 and #1073. It's easy to make a change to the TypeScript declarations and verify that it works for one or more configurations, but end up breaking another configuration. The goal of this change is to have a set of known TypeScript configurations that work. If we discover that another configuration doesn't work, then we can add the configuration to these tests and then go about fixing the TypeScript declarations to support that configuration, while also verifying that whatever change is made doesn't break any other configurations that we know about.
The TypeScript code in each project is not meant to be …

test: verify various typescript configurations

---

dist/purify.cjs.d.ts
dist/purify.es.d.mts
scripts/fix-types.js
src/config.ts
src/purify.ts

Replaces 'trusted-types' import with 'trusted-type/lib', as described at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/trusted-types#library-usage.
In a private project (apologies, I've so far been unable to reproduce the issue in a standalone example) I'm seeing seemingly-unrelated errors from TypeScript after updating to dompurify@v3. The errors all seem related to Redux usage. For example:
```bash
src/path/to/file.tsx:550:14 - error TS2554: Expected 1 arguments, but got 0.
550     dispatch(setCurrentConnection())
~~~~~~~~~~~~~~~~~~~~
```
It's not obvious to me how trusted-types would affect Redux or other types, but the only two ways I've found to avoid the error were to (1) make this change to dompurify, or (2) to use `package.json#resolutions` to point to a …

fix(trusted-types): Use 'trusted-types/lib'

---

README.md

Mentioning successful test on `Node.js v0.6.2` seems outdated.

chore(docs): remove obsolete mention
