LICENSE, bower.json, package.json
=> Change from MPL-2.0 to a dual license of Apache-2.0 and MPL-2.0

src/purify.js
https://github.com/cure53/DOMPurify/issues/131
=> Allow data URIs for audio, video, and source tags in addition to img tags

package.json, test/jsdom-node.js
Also see #149 
Perhaps you could push this branch as a branch on cure53/DOMPurify to make sure that travis succeeds? This PR will of course also trigger a travis run, but without the karma tests.
=> Run tests using jsdom on travis and the local-test script

README.md
=> Update README.md with working node.js example and re-phrasing of requirements

.travis.yml, package.json
This is a WIP for basing a discussion upon over at #156.
=> Refactor run scripts and add build matrix.

demos/hooks-mentaljs-demo.html, demos/lib/Mental.js
Updated mental to latest version. Added parseInnerHTML function to
handle innerHTML assignments.
=> Updated mentaljs demo and library

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Based on #189 this PR serves at a start for issue and pull request templates. Please give feedback 👍
=> Add pull request and issue templates

src/purify.js
It's safer to feature detect where possible, which we can do for the Firefox bug but not for the Safari bug. So let's default to not using `DOMParser`, unless we detect we need it.
I'm still not 100% happy – the reason the `DOMParser` code was [added in the first place](https://github.com/cure53/DOMPurify/releases/tag/0.6.7) was because `innerHTML` in FF uses a different parser when compared to `document.write` (it seems like `innerHTML` may always use the quirks-mode parser?), and so this could introduce a bug if you sanitised the DOM tree generated from this, then used the HTML representation with `document.write`. But by switching to the other parser, it strikes me there may be a vector out there now which parses fine with `DOMParser` but will cause a security hole when passed to …
=> Feature detect when to use DOMParser

test/karma.conf.js, test/purify.min.spec.js, test/purify.spec.js
> This pull request fixes and tweaks the karma config.
Still a bit in the dark but hopefully getting closer.
1. Tweaks the `preprocessor` entry to match the file glob (just a guess)
2. Changes the spec setup files to use ESM
👍 Feel free to merge this 🥇 Let's see what this does. Otherwise I'll poke around the karma config some more. Sorry for the hassle.
=> Fix karma config

rollup.config.js, test/karma.conf.js, test/purify.min.spec.js, test/purify.spec.js, yarn.lock
> This pull request fixes karma setup with rollup.
1. Moves the specific rollup setup for karma to the karma.config.js
2. Fixes using relative imports for the test setup
Just another try. It's really a bit of poking. I will have to leave the keyboard after this until tonight. I hope that's okay but I'll get to it again then.
=> Fix and refactor karma config and setup with rollup

test/karma.conf.js, test/karma.custom-launchers.config.js
Will run FF tests on all node versions
Will run BS tests on master
=> test: on firefox for all node versions

test/test-suite.js
=> Add a test for #283

src/purify.js
This pull request is a prototype for in-place sanitization.
Sample implementation for #288.
=> Sample implementation for IN_PLACE

demos/lib/Mental.js, website/index.html
This pull request fixes a couple missing variable declarations.
Logically, there should be no change.
This is really just a code cleanup.
I'm not sure?
None
=> Add missing var declarations

demos/hooks-target-blank-demo.html
This pull request fixes for Reverse Tabnabbing
=> Fixed security issue in demo (Reverse Tabnabbing)

demos/README.md, package.json, scripts/build-demo.js, scripts/server.js, test/test-suite.js
> This pull request applies prettier to more things.
I noticed that we don't auto-format as much as we could. Just a suggestion to broaden it a bit.
=> chore: apply prettier to more

README.md, SECURITY.md
Hi folks!
This pull request updates the capitalization of Fastmail in README.md and SECURITY.md.
This is a cosmetic documentation change.
- Verify validity of documentation change
None (as far as I know)
=> Update Fastmail capitalization

website/index.html
Added the checkbox because it's a pain in the ass to test the demo clicking that button all the time or having to modify the DOM to add the onkeyup event every time.
=> Added auto convert checkbox

package.json
See https://docs.npmjs.com/cli/v6/configuring-npm/package-json#license
=> Fix multi-license declaration

test/test-suite.js
Added tests for the fix for #596.
=> added tests for ALLOWED_CUSTOM_ELEMENTS config option

README.md, test/karma.custom-launchers.config.js
Ran `npm run format`.
I found some files are not formatted.
=> chore: run format

.github/workflows/build-and-test.yml, README.md, package-lock.json, package.json
I changed the npm scripts and CI settings to use only npm. I tested the change with [this pull request](https://github.com/is2ei/DOMPurify/pull/1).
#616
=> Use only npm

package-lock.json, package.json
This PR updates `karma-chrome-launcher` version to the latest version.
https://github.com/karma-runner/karma-chrome-launcher/blob/master/CHANGELOG.md
=> chore: bump karma-chrome-launcher

README.md
This PR updates README to describe `ALLOW_ARIA_ATTR` option.
README does not mention the option.
=> docs: describe ALLOW_ARIA_ATTR option

package-lock.json, package.json
This PR updates the outdated jsdom package version.
- https://github.com/jsdom/jsdom/blob/master/Changelog.md
=> chore: bump jsdom

package-lock.json, package.json
This PR updates `karma` version.
- https://github.com/karma-runner/karma/blob/master/CHANGELOG.md
=> chore: bump karma

test/test-suite.js
This PR formats JS files.
`$ npm run format` produces diffs.
=> chore: format js

package-lock.json, package.json
This PR updates the` eslint-config-prettier` version.
- https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md
=> bump eslint-config-prettier

website/index.html
=> chore: updated website version info

LICENSE
=> docs: Updated the year in LICENSE file

README.md
Document removed options.
Make it easier to migrate from older versions.
- Are there other removed options?
=> feat(docs): add removed options

website/index.html
Declare demo website as english.
Recommendation by W3C.
- show in browser
=> feat(website): add lang attribute to declare language

test/karma.custom-launchers.config.js
=> fix: typo in karma.custom-launchers.config.js

package.json
=> Move @types/trusted-types to optionalDependencies

src/tags.ts
Removed redundant comment
Deleted Redundent comment
Reading through the code to determine if we should use this library, I found a redundant comment. Removing this for readability. 
Deleted a comment
=> Removed redundant comment

README.md
Just typo in readme nodejs version.
Nothing important.
Read.
=> fix(docs): typo nodejs version

README.md
=> fix(docs): add missing bracket
